### ISSUE TITLE
Support for ASKEM Model Representation

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/simulation-service#25]
This issue is to ensure that the sim service can read in the petrinet in [AMR format](https://github.com/darpa-askem/model-representations) in lieu of a py-acset.

It's likely that @mehalter can point us to a converter that we could just port in here.

**Comment by fivegrant** [comment]
Just to clarify that for a given Model Representation TA3a expects a conversion to an acset as opposed to the model representation itself.

**Comment by brandomr** [comment]
@mehalter could you point us to the converter you put together, even if it's WIP?

**Comment by mehalter** [comment]
I am still working on a generic way to do updates to this as we use our API to do structural changes. We will basically need to be able to update the properties for each transition and state after we do structural changes. But this will at least be able to go from JSON -> AlgebraicPetri

**Comment by fivegrant** [comment]
Thanks, I'll include that code verbatim once I've merged #24. Let me know though if you set up some kind of ASKEMLab repo and i could just be a consumer of that instead.

**Comment by fivegrant** [comment]
I believe this issue is blocked until the different semantics are included in the model representation (closest issue I could find is [mr#22](https://github.com/DARPA-ASKEM/Model-Representations/pull/22)).

**Comment by brandomr** [comment]
The petrinet schema is now stable: https://github.com/DARPA-ASKEM/Model-Representations/blob/main/petrinet/petrinet_schema.json
