### ISSUE TITLE
Return intermediate results through RabbitMQ

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/simulation-service#34]
#35 provides a context object that contains the job id and the RabbitMQ hook. Basic publish functionality should be possible by giving the provided function a dictionary. 

---

@joshday's edits:

 The `callback` in the `solve(::Operation; callback::DiscreteCallback)` methods for `Simulate`/`Calibrate`/`Ensemble` works out of the box with `SciMLBase.solve`.  

- Callback support needs to get added to EasyModelAnalysis (https://github.com/SciML/EasyModelAnalysis.jl/issues/158 is blocking for `(ensemble)-calibrate`).

- The callback probably needs to be modified for `Ensemble{T}` to identify the component of the ensemble.

### Endpoints to return intermediates for:

- [x] `simulate`
- [x] `calibrate`
- [x] `ensemble-simulate`
- [x] `ensemble-calibrate`

**Comment by fivegrant** [comment]
@joshday @Tom-Szendrey @mj3cheun what's the status of this in the HMI?

**Comment by Tom-Szendrey** [comment]
> @joshday @Tom-Szendrey @mj3cheun what's the status of this in the HMI?

I have a draft PR up right now to pull this for the HMI
Just want to test a tad more. Currently we are only receiving `job_id` and `progress` as i think youre aware

https://github.com/DARPA-ASKEM/Terarium/pull/1684#pullrequestreview-1574091447

**Comment by fivegrant** [comment]
@Tom-Szendrey is this for the SciML Service as well or just the PyCIEMSS Service?

**Comment by Tom-Szendrey** [comment]
At the moment just pyciemss sorry for the confusion

**Comment by joshday** [comment]
What intermediate information does Terrarium want us to send?  

I know I've already asked various people about this on calls/slack, but I've lost the thread (sorry!) and we should have it written down here.

**Comment by joshday** [comment]
Closing this since the functionality is there.  Will open new issues for bug fixes.
