### ISSUE TITLE
Update Simulation-service to align with new model schema

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/simulation-service#40]
FYI: there's been little progress with a new AMR so I can't imagine this will be started let alone completed (by me at least @tangopapatime) before I start my Vacation next week.

**Comment by JeffBezanson** [comment]
Is this the same as #25?

**Comment by fivegrant** [comment]
yes i'm pretty sure this is a duplicate

**Comment by fivegrant** [comment]
@dgauldie i added #25 to the "Feature Planning" project so you can still track this issue. if this isn't right we can reopen this issue
