### ISSUE TITLE
Timestep interval not always being respected

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/simulation-service#63]
@joshday I think with the intermediate hook some of addiotional steps are being injected that are not intervals. I could do some post processing on the dataset to strip them out (filter rows using `isinteger`) but it might better to fix this in the operation itself. Either way works for me.

**Comment by ChrisRackauckas** [comment]
This was due to the callback and handled in https://github.com/DARPA-ASKEM/simulation-service/pull/94
