### ISSUE TITLE
Return observables in results

### ISSUE THREAD

**Issue by joshday** [DARPA-ASKEM/simulation-service#65]
We currently are not calculating the "observables" from the AMR.  

The rewrite (https://github.com/DARPA-ASKEM/simulation-service/pull/64) should enable this pretty easily.

**Comment by JeffBezanson** [comment]
Most of this is in #67, but we need another small piece to get the observed values into the solution dataframe.

**Comment by JeffBezanson** [comment]
Fixed by #68.
